# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x05users\"\x1e\n\x0bUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"<\n\x0cUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"\x11\n\x0fUserListRequest\"1\n\x10UserListResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t2\x83\x01\n\x0bUserService\x12\x32\n\x07GetUser\x12\x12.users.UserRequest\x1a\x13.users.UserResponse\x12@\n\x0bStreamUsers\x12\x16.users.UserListRequest\x1a\x17.users.UserListResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERREQUEST']._serialized_start=24
  _globals['_USERREQUEST']._serialized_end=54
  _globals['_USERRESPONSE']._serialized_start=56
  _globals['_USERRESPONSE']._serialized_end=116
  _globals['_USERLISTREQUEST']._serialized_start=118
  _globals['_USERLISTREQUEST']._serialized_end=135
  _globals['_USERLISTRESPONSE']._serialized_start=137
  _globals['_USERLISTRESPONSE']._serialized_end=186
  _globals['_USERSERVICE']._serialized_start=189
  _globals['_USERSERVICE']._serialized_end=320
# @@protoc_insertion_point(module_scope)
