version: '3.8'

services:
  # Microservice 1: User Service
  user-service:
    build:
      context: .
      dockerfile: ./service1_user/Dockerfile
    container_name: python_user_service
    ports:
      - "50051:50051" # Expose gRPC cho bên ngoài (nếu test tool)
      - "8001:8001" # Expose FastAPI
    networks:
      - micro-network
    restart: always

  # Microservice 2: Order Service (sử dụng User Service)
  order-service:
    build:
      context: .
      dockerfile: ./service2_order/Dockerfile
    container_name: python_order_service
    ports:
      - "8002:8002" # Expose FastAPI 
    environment:
      # Truyền URL nội bộ của Docker. `user-service` là tên của Service ở trên cùng network
      - USER_SERVICE_URL=user-service:50051
    networks:
      - micro-network
    depends_on:
      - user-service
    restart: always

# Khởi tạo một mạng Docker ảo riêng
networks:
  micro-network:
    driver: bridge
